const ReposTypes = {
  SET_STATE: '@@repos/SET_STATE',
  FETCH_REPOS_REQUEST: '@@repos/FETCH_REPOS_REQUEST',
  FETCH_REPOS_SUCCESS: '@@repos/FETCH_REPOS_SUCCESS',
  FETCH_REPOS_FAILURE: '@@repos/FETCH_REPOS_FAILURE',
  FETCH_MORE_REPOS_REQUEST: '@@repos/FETCH_MORE_REPOS_REQUEST',
  FETCH_MORE_REPOS_SUCCESS: '@@repos/FETCH_MORE_REPOS_SUCCESS',
  FETCH_MORE_REPOS_FAILURE: '@@repos/FETCH_MORE_REPOS_FAILURE',
};

export default ReposTypes;
